"""
This is a setup.py script generated by py2applet for generating bundled OS X THiNX Agent

Usage:
    python setup.py py2app
"""

import os

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['lock-large.png']
RESOURCES = []

files = ['./assets/logo.png']

RESOURCES.extend(files)

OPTIONS = {
    'resources': RESOURCES
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
